### ISSUE TITLE
The http_listener remaps the `Date` header to `Data`

### ISSUE THREAD

**Issue by bileblight** [microsoft/cpprestsdk#1208]
When receiving a request with the cpprestsdk http_listener, the `Date` header from the sent request is mapped to the `Data` header in the `http_request` of cpprestsdk.

According to line `47` in `Release/src/http/listener/http_server_httpsys.cpp`, the values of `HttpServerAPIKnownHeaders` are supposed to match the values of the `_HTTP_HEADER_ID` enum (defined [here](https://docs.microsoft.com/en-us/windows/win32/api/http/ne-http-_http_header_id)). `HttpServerAPIKnownHeaders` states `Data` as the third entry, whereas `_HTTP_HEADER_ID` lists `Date`.

If someone could please verify that the issue is indeed present and that the cuplrit is the suggested typo, I would gladly provide a pullrequest to be merged into this project.

**Comment by garethsb-sony** [comment]
I agree, that looks like a typo!!

At the same time, it would be nice to fix `"Www-Authenticate"` to the canonical `"WWW-Authenticate"` slightly further down the same file, even though header names are compared case-insensitively.

And both fixes should please also be applied to Release\tests\functional\http\utilities\test_http_server.cpp.

**Comment by garethsb-sony** [comment]
Actually, the `HttpServerAPIKnownHeaders` is more broken than it first appears, since the HTTP Server API `HTTP_HEADER_ID` is not a simple auto-numbered `enum` but rather includes common, and request- and response-specific headers in a single `enum` with constant initializers for the defined indices in the `HTTP_REQUEST_HEADERS::KnownHeaders` _and_ the `HTTP_RESPONSE_HEADERS::KnownHeaders` arrays. For example, both `HttpHeaderAcceptCharset` (the request header, `"Accept-Charset"`) and `HttpHeaderAge` (the response header, `"Age"`) are given the same value, `21`.

As it stands, `HttpServerAPIKnownHeaders` is only used to parse request headers, so rather than create a new structure that works for both, I propose to remove the response-specific headers and clarify its intended use. PR on its way...
