### ISSUE TITLE
Ubuntu Package broken?

### ISSUE THREAD

**Issue by Naville** [microsoft/cpprestsdk#1317]
Not sure if I'm the only one. But on my clean Ubuntu 19.04 VPS created on Vultr.``find_package(cpprestsdk REQUIRED)`` is not able to find cpprestsdk even when I already installed it with ``apt install libcpprest-dev``.

```
Make Error at CMakeLists.txt:16 (find_package):
  By not providing "Findcpprestsdk.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "cpprestsdk", but CMake did not find one.

  Could not find a package configuration file provided by "cpprestsdk" with
  any of the following names:

    cpprestsdkConfig.cmake
    cpprestsdk-config.cmake

  Add the installation prefix of "cpprestsdk" to CMAKE_PREFIX_PATH or set
  "cpprestsdk_DIR" to a directory containing one of the above files.  If
  "cpprestsdk" provides a separate development package or SDK, be sure it has
  been installed.


```

**Comment by c72578** [comment]
Please have a look at https://github.com/microsoft/cpprestsdk/issues/686#issuecomment-440622042

**Comment by Naville** [comment]
@c72578 Yeah but I assume this is something that should be fixed instead of "workaround"?

**Comment by c72578** [comment]
Yes, this should definitely be fixed - in the Ubuntu package.

The final decision, where the cmake files get installed is made by the package of the Linux distribution. For instance in the package for Fedora Linux, we use `-DCPPREST_EXPORT_DIR` to define, where the cmake files get installed [1].
So, this issue should be reported to the packagers of the Ubuntu package. As soon as this has been reported, it makes sense to put a link in #686 so that people coming here to look for a solution can follow.

[1] https://src.fedoraproject.org/rpms/cpprest/blob/master/f/cpprest.spec
