### ISSUE TITLE
The Readme mentions VCPKG on Windows explicitly. Does the Casablanca VCPKG package have issues on Linux/macOS?

### ISSUE THREAD

**Issue by pratikpc** [microsoft/cpprestsdk#1504]
In the README there is the line

> With vcpkg on Windows

> PS> vcpkg install cpprestsdk cpprestsdk:x64-windows

I could run vcpkg install cpprestsdk on a Linux based system to check but it's quite possible the reason Windows is only mentioned might be because some portions might not work or the Documentation needs to be edited (hopefully the latter)

**Comment by c72578** [comment]
Linux based systems are supported as well using vcpkg.
Under Linux, building cpprestsdk works properly using vcpkg. A linux build is also part of the vcpkg CI.
See vcpkg - cpprestsdk commit history:
https://github.com/microsoft/vcpkg/commits/master/ports/cpprestsdk/portfile.cmake

The reason why Windows is mentioned here explicitly is because vcpkg is a straight forward way, to build cpprestsdk on Windows. Otherwise it can be quite a bit of an effort to build all the dependencies and cpprestsdk manually on Windows ...

On the other hand, a current version of cpprestsdk is packaged by many Linux distributions and can be installed out of the box. No need to compile it - it many cases. However, it works fine too under Linux to build it using vcpkg.

**Comment by pratikpc** [comment]
Thanks!
