### ISSUE TITLE
Stringify/parse C++ objects like in JavaScript's JSON.stringify()/JSON.parse()

### ISSUE THREAD

**Issue by CodingSpiderFox** [Microsoft/cpprestsdk#403]
As I don't want to code the whole serialization / deserialization of an object with many members by handling every value for that member, I want to have achieve this by calling one method.
I would not like to do implement this for every class member because
a) It takes too much time to implement
b) Takes much effort to maintain if a class gets new members etc.

See this example: https://stackoverflow.com/questions/8220130/converting-c-class-to-json
There is an answer (https://stackoverflow.com/a/19974486/4397899) that says ThorsSerializer would be able to do something like that, at least something more beautiful like handling every member value manually in code.

Is something similar to either JavaScript's JSON.stringify()/JSON.parse() or the way ThorsSerializer does it possible with cpprestsdk?

Best regards

**Comment by ras0219-msft** [comment]
We unfortunately don't have machinery built-in to C++ REST SDK to automatically generate (de)serialization functions like this.

However, it's completely supported to bring your own JSON framework (such as ThorsSerializer or RapidJSON) that does support this! Just use `.extract_string()` instead of `.extract_json()` and pass it to the framework of your choice.

**Comment by CodingSpiderFox** [comment]
Ok, thanks anyway
