### ISSUE TITLE
std::wstring Access violation

### ISSUE THREAD

**Issue by CfirTsabari** [Microsoft/cpprestsdk#452]
hello,
i have tried to start using this framework.
i am using VS 2013 on windows 7 x64.
in order to use the framework,first i got vcpkg(which i have installed using VS 2017 build tools),afterwards i used it to to get the framework.
so :
1: I opened a new console application.
2: I have added the include directory
3:I have added the libraries directory.
4: i have added the cpprest lib file to the AdditionalDependencies(inside Linker->Input).
5-i have copied the dll files to the output folder.

but i am receiving an exception every time i try to run it, it's basically fail over one line:
```cpp
http_client test_client(U("http://www.bing.com/"));
```
what i am receiving is :
Unhandled exception at 0x000007FEDBF6D164 (msvcr120d.dll) in ConsoleApplication4.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
i have attached the [Call Stack](https://github.com/Microsoft/cpprestsdk/files/1034036/callstack.txt), it's look related to the std::wstring but i couldn't figured that out.

Did i missed something at the installation or configuration process? or is this a bug?

**Comment by ras0219-msft** [comment]
Hi @CfirTsabari,

Unfortunately, you can't use C++ types across different Visual Studio versions (with the recent exception of 2015 and 2017).

The best way to fix this is to install the free Visual Studio 2017 community edition (the installation process is much nicer now -- try it out!).

Otherwise, you will need to use our NuGet packages or build from source using CMake or MSBuild.
