### ISSUE TITLE
http listener rejects square brackets

### ISSUE THREAD

**Issue by khalid80** [Microsoft/cpprestsdk#625]
I am trying the http listener and its rejecting any call which has square bracket
when fetching http://localhost:8080/Test/{"data":["1"]} it responed with "provided uri is invalid:"

**Comment by garethsb-sony** [comment]
That's because your URL is invalid. See e.g. https://perishablepress.com/stop-using-unsafe-characters-in-urls/ for an explanation of which characters like {}[] must be %-encoded, if you really want to do something like include JSON in your URL. On the other hand, maybe you would be better sending the JSON as the body of the request...

**Comment by khalid80** [comment]
but even after encoding {"values":["1"]}  to "%7B%22values%22%3A%5B%221%22%5D%7D", its still rejected, but other servers accept it, Like WCF ServiceHost.

**Comment by garethsb-sony** [comment]
That encoded path should be accepted... Are you still seeing the same message "provided uri is invalid: ..."?

**Comment by khalid80** [comment]
Actually no, i am getting 500 error now.

**Comment by garethsb-sony** [comment]
I think this needs to be re-opened. There _is_ an issue that needs fixing here (probably more than one in fact).

The implementation of ``web::http::http_request::relative_uri()`` decodes the request URL and then erases the prefix of the listener base path.

This is the first issue - the behaviour depends on whether the listener base path was set up with, in our example, http://localhost:8080/Test/ or http://localhost:8080/Test, without the trailing slash. (It's not as bad as it might seem, as http_listener identifies that http://host/foo is a prefix of http://host/foo/bar but not of http://host/foobar before this point.)

The remaining path string is then re-encoded.

Here is a second issue. Since we know that this is a path, ``uri::encode_uri(..., uri::components::path)`` would be better than the default (``full_uri``) used currently. In either case however, a %3A in the original URL becomes an unencoded colon (:), since colon is a valid path character.

A ``web::uri`` is then constructed from this encoded relative path.

Here's the third issue, where the 500 error comes from. Although we know we want a relative URL at this point, the ``web::uri`` constructor attempts to automatically determine whether the passed string is an absolute or relative URI. In the case we're considering, I suspect the listener base path was http://localhost:8080/Test/ (with the trailing colon) and the relative path is for example "%7B%22values%22:%5B%221%22%5D%7D". Here, the first colon precedes the first slash. This is not a valid relative URL, an exception is thrown from the constructor and a 500 error results.

Quote from RFC 3986:

>    A path segment that contains a colon character (e.g., "this:that")
>    cannot be used as the first segment of a relative-path reference, as
>    it would be mistaken for a scheme name.  Such a segment must be
>    preceded by a dot-segment (e.g., "./this:that") to make a relative-
>    path reference.

I'm not sure what the correct fix is here. Perhaps ``relative_uri()`` could construct a ``uri`` with a "./" prefix in this case, or it could use the constructor taking ``details::uri_components``. The current behaviour does seem like a bug however.

**Comment by garethsb-sony** [comment]
There's a more fundamental question. Given a listener base path of "/path1" or "/path1/", and a request_uri of "/path1/path2", should the resulting ``relative_uri`` be "/path2" or just "path2"?

The latter seems more correct to me w.r.t. RFC 3986, but is a change of behaviour.

@ras0219-msft What do you think about this whole issue?
