### ISSUE TITLE
Missing 'int_type' definition in "streams.h" file

### ISSUE THREAD

**Issue by juntek** [Microsoft/cpprestsdk#628]
Last definition of class template _type_parser_ (compiled conditionally for _WIN32) lacks 'int_type' definition used in the __accept_char_ static method.

Simple copy of:
_typedef typename concurrency::streams::streambuf<CharType>::int_type int_type;_
from the class template above solves this issue.

platform: WIN32, x86
compiler: VS2017 Community

**Comment by garethsb-sony** [comment]
Good spot. The typedef wasn't required before the recent commit, because int_type could be discovered from the base class, in each of the three full specialisations. Now that the base class is dependent on the template parameter, the base class scope is not examined; the typedef is the conventional solution.

**Comment by bolbol2night** [comment]
I just checkout the code and the issue is still there.
I solved by adding this line of code at the begining of class type_parser:
`typedef typename concurrency::streams::streambuf<CharType>::int_type int_type;`
