### ISSUE TITLE
Master build fails due to a bug in the websocketpp version you have included with cpprestsdk

### ISSUE THREAD

**Issue by hdoradu** [Microsoft/cpprestsdk#640]
The problem is here:
https://github.com/Microsoft/cpprestsdk/blob/6ebb942f20a3708dc57ff6fe66b2e738b0b741a2/Release/libs/websocketpp/websocketpp/transport/asio/connection.hpp#L425
And it was fixed here: https://github.com/zaphoyd/websocketpp/commit/ed45dcc6171ce1a64f4d38102fa9db890c0486ad

Is there a plan to upgrade [websocktepp](https://github.com/Microsoft/cpprestsdk/tree/master/Release/libs/websocketpp), or maybe just apply this patch?

**Comment by ras0219-msft** [comment]
We recommend getting websocketpp through your package manager of choice instead of using the embedded copy -- our cmake build will automatically do this if it is made available.

Our embedded copy exists to continue supporting cases such as our MSBuild scripts which use prebuilt (and old) copies of boost which are compatible.
