### ISSUE TITLE
Compile error when using along with boost (mongocxx)

### ISSUE THREAD

**Issue by convexbytes** [Microsoft/cpprestsdk#647]
If cpprestsdk is included before boost, it causes a compilation error. This happens because cpprestsdk defines macro U in basic_types.h:

```
#ifndef _TURN_OFF_PLATFORM_STRING
#define U(x) _XPLATSTR(x)
#endif // !_TURN_OFF_PLATFORM_STRING
```

 but boost uses "U" for template typenames (type_traits.hpp):
```
   #if defined(BOOST_MOVE_TT_CXX11_IS_COPY_CONSTRUCTIBLE)
      template<class U> static typename add_reference<U>::type source();
      static no_type test(...);
      #ifdef BOOST_NO_CXX11_DECLTYPE
         template <class U>
         static yes_type test(U&, bool_<sizeof(U(source<U>()))>* = 0);
      #else
         template <class U>
         static yes_type test(U&, decltype(U(source<U>()))* = 0);
      #endif
      static const bool value = sizeof(test(source<T>())) == sizeof(yes_type);
   #else

```

**Comment by garethsb-sony** [comment]
Does defining ``_TURN_OFF_PLATFORM_STRING`` while building your project (or just a few source files) work for you? I think the ``U("foo")`` macro is too convenient to give up but in cases like this is always going to cause problems. This is covered in the [FAQ](https://github.com/Microsoft/cpprestsdk/wiki/FAQ#what-is-utilitystring_t-and-the-u-macro), but a note at the definition of ``U`` in the code might be helpful. This has [come up several times before](https://github.com/Microsoft/cpprestsdk/search?q=_TURN_OFF_PLATFORM_STRING&type=Issues).

Internally C++ REST SDK mostly (but not quite always...) uses the more verbose but less problematic ``_XPLATSTR("foo")`` directly rather than ``U("foo")``.

**Comment by convexbytes** [comment]
Thank you, I missed that part in the FAQ. Indeed, U is useful and I decided to keep it. For the moment I changed the order of include files and it compiled fine.

**Comment by VeaaC** [comment]
This makes it indeed hard to use this library together with most C++ libraries (template parameters are usually named T, U, V). This includes Boot, and Intel TBB amongst others.

While the U macro is somewhat convenient for you, it is a major inconvenience for users of the library. Does it make sense to reconsider this?
