### ISSUE TITLE
Performance issue? http request takes too much time

### ISSUE THREAD

**Issue by yumdayum** [Microsoft/cpprestsdk#661]
When I perform any type of PUT/POST/GET it can sometime take more than a minute before it can retrieve a response. Is that something expected?

Here is just a sample code of my request
```
	http_client client(url);
	client.request(methods::POST, L"", payload.serialize(), CONTENT_TYPE_JSON)
		.then([](http_response response) {
		//Can add logging for the response code
		if (response.status_code() == status_codes::OK) {
			std::cout << "Response code OK";
		}
		else {
			std::cout << response.status_code() << "\n";
		}
	});
```

anyone ever ran into this kind of issue?

**Comment by PBRCW** [comment]
No, that sounds strange! Never faced such an effect. Did you take a look at the network level what's going on with Wireshark and/or Fiddler? This might give you a hint if the problem is on client or server side or maybe even on some other network equipment. "More than a minute" sounds more like a network timeout to me...
