### ISSUE TITLE
Compilation errors when using cpprestsdk together with C++ template libraries

### ISSUE THREAD

**Issue by VeaaC** [Microsoft/cpprestsdk#692]
cpprestsdk is defining a U macro that breaks when combined with many popular C++ libraries: template parameters are usually named T, U, V. This includes Boot, and Intel TBB amongst others.

While the U macro is somewhat convenient for you, it is a major inconvenience for users of the library. Does it make sense to reconsider using it?

Also: Related to closed issue #647

**Comment by garethsb-sony** [comment]
As described in #647, does defining ``_TURN_OFF_PLATFORM_STRING`` while building your project (or just a few source files) work for you? This is covered in the [FAQ](https://github.com/Microsoft/cpprestsdk/wiki/FAQ#what-is-utilitystring_t-and-the-u-macro), but a note at the definition of ``U`` in the code might be helpful?

**Comment by VeaaC** [comment]
Not really, it fails to compile in that case (U not defined anywhere, but still used), e.g. in
https://github.com/Microsoft/cpprestsdk/blob/master/Release/include/cpprest/details/http_helpers.h

**Comment by garethsb-sony** [comment]
Those instances of ``U()`` in the library's own headers should be replaced, agreed. I'll make a PR for that.

**Comment by VeaaC** [comment]
Also: If "U" is only used in tests, maybe disable it by default, and only enable it in tests (e.g. in a special header file for tests)?

**Comment by garethsb-sony** [comment]
The ``U`` is currently only used in that one public header (and that is definitely a bug in my opinion, fixed by #693), but it's used all over the implementation, tests and samples. Personally I agree switching the definition of ``U`` from on-by-default to off-by-default is worth the maintainers considering but it would break a lot of existing user code, so there's a trade-off.
