### ISSUE TITLE
cpprestsdk crash  in vs 2015 or 2017

### ISSUE THREAD

**Issue by stonetang** [Microsoft/cpprestsdk#719]
int main() {
    concurrency::streams::stringstreambuf buffer;

    web::http::client::http_client_config config;
    config.set_validate_certificates(false);

    try {
		std::wstring baseUrl = U("https://nboptest.gf.com.cn");
		utility::char_t * xx = U("https://nboptest.gf.com.cn");
		web::http::uri uri(xx);
        web::http::client::http_client raw_client(uri, config);   // 这里crash:  std::bad_array_new_length

        web::http::MultipartParser parser;
        parser.AddParameter("operatorNo", "8888");
        parser.AddParameter("password", "*FS'@ru-/\"");
        parser.AddParameter("opStation", "NBOP-IP:10.2.238.182,MAC:08:6d:41:c1:44:b2,HDD:S1W1NYAH325711,LH:nboptest.gf.com.cn");
        parser.AddParameter("opEntrustWay", "v");

        std::string boundary = parser.boundary();
        std::string body = parser.GenBodyContent();

        web::http::uri_builder builder(U("api/nbop/nbopuserright/1.0.0/userright/userAuth"));
        // builder.append_query(U("q"), U("cpprestsdk github"));
		std::string path(builder.to_string().begin(), builder.to_string().end());
        web::http::http_response response = raw_client.request(web::http::methods::POST, path, body, "multipart/form-data; boundary=" + boundary).get();
        // Write response body into the file.
        response.body().read_to_end(buffer).get();
        std::string& str = buffer.collection();
        std::cout << str << std::endl;

    } catch (std::exception & e) {
        std::cout << "exception: " << e.what() << std::endl;
    }

    return 0;
}

**Comment by stonetang** [comment]
web::http::client::http_client raw_client(uri, config);  => this code was crashed

**Comment by stonetang** [comment]
exception: std::bad_array_new_length

**Comment by garethsb-sony** [comment]
Are you certain the exception comes from that line, not the previous one?

```C++
	std::string path(builder.to_string().begin(), builder.to_string().end());
```

The ``to_string`` function returns a temporary value. Therefore you are passing the begin iterator of one temporary and the end iterator of a different one to the ``string`` constructor. Moreover, since ``to_string`` returns ``utility::string_t`` which ought to be ``std::wstring`` on Windows, and that's also the type of the ``path_query_fragment`` argument to the ``http_client::request`` function anyway, this probably isn't what you wanted to write for several reasons.

If you just pass ``builder.to_string()`` in the ``raw_client.request(...)`` call what happens?

**Comment by gaurav1436** [comment]
I can't find the MultipartParser.. is this function included in sdk

**Comment by BillyONeal** [comment]
Seems the line @garethsb-sony indicated must be to blame.
