### ISSUE TITLE
Ubuntu 18.04 - Add the installation prefix of "libcpprest-dev" to CMAKE_PREFIX_PATH

### ISSUE THREAD

**Issue by adamzerella** [Microsoft/cpprestsdk#763]
I am using Ubuntu 18.04 with `libcpprest-dev 2.10.2-6` from [bionic/universe](https://packages.ubuntu.com/bionic/libcpprest-dev) and CMake `v3.10`. CMake is unable to build due to a missing package configuration file:

**Error:**
> CMake Error at CMakeLists.txt:31 (find_package):
>   By not providing "Findlibcpprest-dev.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "libcpprest-dev", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "libcpprest-dev"
>   with any of the following names:
> 
>     libcpprest-devConfig.cmake
>     libcpprest-dev-config.cmake
> 
>   Add the installation prefix of "libcpprest-dev" to CMAKE_PREFIX_PATH or set
>   "libcpprest-dev_DIR" to a directory containing one of the above files.  If
>   "libcpprest-dev" provides a separate development package or SDK, be sure it
>   has been installed.

**CMakeLists.txt:**

> cmake_minimum_required ( VERSION 3.10 )
> 
> project ( REDACTED )
> 
> set( CMAKE_BINARY_DIR ${CMAKE_SOURCE_DIR}/bin/ )
> set( EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin/ )
> set( LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin/lib/ )
> 
> if( APPLE )
> set( OPENSSL_ROOT_DIR /usr/local/opt/openssl )
> set( OPENSSL_LIBRARIES /usr/local/opt/openssl/lib )
> elseif( UNIX AND NOT APPLE )
> // TODO
> elseif( MSVC )
> // TODO
> endif()
> 
> if( OPENSSL_ROOT_DIR ) 
> find_package(curl REQUIRED)
> endif()
> 
> if ( APPLE )
> find_package( cpprestsdk REQUIRED )
> elseif ( UNIX AND NOT APPLE )
> find_package( libcpprest-dev REQUIRED )
> endif()
> 
> find_package(Boost 1.67.0 COMPONENTS system)
> 
> include_directories( ${PROJECT_SOURCE_DIR}/include/ )
> 
> link_directories( ${PROJECT_SOURCE_DIR}/lib/ )
> 
> add_executable( REDACTED ${PROJECT_SOURCE_DIR}/src/Main.cpp )
> 
> set_property( TARGET REDACTED PROPERTY CXX_STANDARD 17 )
> 
> target_link_libraries ( REDACTED curl cpprestsdk::cpprest Boost::system)

Upon inspection the only CMake files located with the project are
`dpkg -L libcpprest-dev`:

/usr/lib/x86_64-linux-gnu/cmake/cpprestsdk-config.cmake
/usr/lib/x86_64-linux-gnu/cmake/cpprestsdk-targets-none.cmake
/usr/lib/x86_64-linux-gnu/cmake/cpprestsdk-targets.cmake

Setting `CMAKE_PREFIX_PATH` doesn't seem to resolve the issue... What am I missing here?

**Comment by EdgarWahn** [comment]
Do I understand it right that you want to include cpprest into your project as an submodule?
If yes, I had problems with that as well. I made some modifications to the CMakeLists.txt and added two files. Now it works almost flawless for me. I forked the project, but due to some problems running the latest patches from the original project I did not push my changes... Far from perfect, but works at least for me.
Maybe you get the idea and it helps (note I pinned by version to 2.10.1):

CMakeLists.txt:
change the project keywords:
project(cpprest VERSION 2.10.1 LANGUAGES C CXX)

add explicit set statements for the version:
set(cpprest_VERSION 2.10.1)
set(cpprest_VERSION_MAJOR 2)
set(cpprest_VERSION_MINOR 10)
set(cpprest_VERSION_PATCH 1)
set(cpprestsdk_VERSION 2.10.1)
set(cpprestsdk_VERSION_MAJOR 2)
set(cpprestsdk_VERSION_MINOR 10)
set(cpprestsdk_VERSION_PATCH 1)

add to end of file:
CONFIGURE_FILE(cpprestConfig.cmake.in "${PROJECT_BINARY_DIR}/cpprestConfig.cmake" @ONLY)
CONFIGURE_FILE(cpprestConfigVersion.cmake.in "${PROJECT_BINARY_DIR}/cpprestConfigVersion.cmake" @ONLY)

Add two new files (Release folder):
1) "cpprestConfig.cmake.in"
# Compute paths
get_filename_component(CPPREST_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(CPPREST_INCLUDE_DIRS "@CONF_INCLUDE_DIRS@")

# Our library dependencies (contains definitions for IMPORTED targets)
IF(NOT TARGET foo AND NOT ${PROJECT_NAME}_BINARY_DIR)
  include("${CPPREST_CMAKE_DIR}/${PROJECT_NAME}Targets.cmake")
ENDIF()

# These are IMPORTED targets created by ${PROJECT_NAME}Targets.cmake
SET(CPPREST_LIBRARIES ${PROJECT_NAME})

2) "cpprestConfigVersion.cmake.in"
SET(PACKAGE_VERSION "@cpprest_VERSION@")

# Check whether the requested PACKAGE_FIND_VERSION is compatible
IF("${PACKAGE_VERSION}" VERSION_LESS "${PACKAGE_FIND_VERSION}")
  SET(PACKAGE_VERSION_COMPATIBLE FALSE)
ELSE()
  SET(PACKAGE_VERSION_COMPATIBLE TRUE)
  IF("${PACKAGE_VERSION}" VERSION_EQUAL "${PACKAGE_FIND_VERSION}")
    SET(PACKAGE_VERSION_EXACT TRUE)
  ENDIF()
ENDIF()

**Comment by ras0219-msft** [comment]
As is in our README, you need to use
```cmake
find_package(cpprestsdk REQUIRED)
```
instead of searching for `libcpprest-dev`.

**Comment by adamzerella** [comment]
@ras0219 The README clearly states that for Debian/Ubuntu you need to install `libcpprest-dev`. On Ubuntu 18.04 the package is [built from `libcpprest-dev`.](https://packages.ubuntu.com/source/bionic/cpprest) 

The area that is failing is at the:
>elseif ( UNIX AND NOT APPLE )
> find_package( libcpprest-dev REQUIRED )

**Comment by ras0219-msft** [comment]
Yep! The Ubuntu apt-get package name is definitely `libcpprest-dev`. The Homebrew package name is `cpprestsdk`.

However, CMake doesn't use these names for the `find_package()` command -- otherwise they'd be different on every platform! Instead, a single common name is used, which is documented on the readme in our CMake example:
```cmake
cmake_minimum_required(VERSION 3.7)
project(main)

find_package(cpprestsdk REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main PRIVATE cpprestsdk::cpprest)
```

**Comment by adamzerella** [comment]
@ras0219 Ahh my mistake! Good pickup, however changing the package name still results in?

>CMake Error at CMakeLists.txt:27 (find_package):
>By not providing "Findcpprestsdk.cmake" in CMAKE_MODULE_PATH this project
>has asked CMake to find a package configuration file provided by
>"cpprestsdk", but CMake did not find one.
>
>Could not find a package configuration file provided by "cpprestsdk" with
>any of the following names:
>
>cpprestsdkConfig.cmake
>cpprestsdk-config.cmake
>
>Add the installation prefix of "cpprestsdk" to CMAKE_PREFIX_PATH or set
>"cpprestsdk_DIR" to a directory containing one of the above files.  If
>"cpprestsdk" provides a separate development package or SDK, be sure it has
>been installed.

**Comment by ras0219-msft** [comment]
I'm not sure what your `CMAKE_MODULE_PATH` etc are set to, however you can see those files installed in the file list: https://packages.ubuntu.com/bionic/amd64/libcpprest-dev/filelist
```
/usr/lib/x86_64-linux-gnu/cmake/cpprestsdk-config.cmake
/usr/lib/x86_64-linux-gnu/cmake/cpprestsdk-targets-none.cmake
/usr/lib/x86_64-linux-gnu/cmake/cpprestsdk-targets.cmake
```

You can also try out vcpkg[1] which recently added support for Ubuntu.

[1] https://github.com/Microsoft/vcpkg

**Comment by adamzerella** [comment]
@ras0219 Ahhh I think I was having a slow day, setting `set ( CMAKE_PREFIX_PATH /usr/lib/x86_64-linux-gnu/cmake/ )` resolved the issue! Thanks a bunch for the help 👍

**Comment by qingfengxia** [comment]
set ( CMAKE_PREFIX_PATH /usr/lib/x86_64-linux-gnu/cmake/ )   also works for me, but it is not cross platform solution. It also break other Boost components find on Ubuntu 18.04.
