### ISSUE TITLE
Macro U collides with Armadillo

### ISSUE THREAD

**Issue by SanPen** [Microsoft/cpprestsdk#812]
The macro `#define U(x) _XPLATSTR(x)` collides somehow with the linear algebra library Armadillo.

If I rename the macro, it all works.

I think it is worth mentioning.

**Comment by aksswami** [comment]
@SanPen You can add a compiler flag `TURN_OFF_PLATFORM_STRING` as suggested by code comment.

**Comment by d-frey** [comment]
`U` is a really bad name, a user of our library was also using cpprestsdk and we used `U` as the name of a template parameter, think `template< typename T, typename U >`. Later we used `U` as a return type for a function pointer, something like `using func_t = U(*)(int,int);` - and that didn't work because of the macro `U`. Please stop defining macros with extremely common names.

**Comment by damienhocking** [comment]
We redefined it in our code to USTR for exactly this reason.

**Comment by SanPen** [comment]
Exactly, I also changed it to USTR, but whenever I update the code or someone else downloads cpprestskd to use it with my code, they have to rename the macro as well.

So, it would be very helpfull to rename this macro (and potentially others) to something harder to be used by others.

**Comment by ras0219-msft** [comment]
We completely agree that `U(X)` is an inappropriate macro; however changing it would be enormously breaking for existing code -- something we certainly won't do between major versions.

The correct mechanism to address this problem is what @aksswami has suggested: define `TURN_OFF_PLATFORM_STRING` and use `_XPLATSTR` in your own code.
