### ISSUE TITLE
http_listener not working when running under systemd as a service

### ISSUE THREAD

**Issue by cyuanmin** [Microsoft/cpprestsdk#827]

**Comment by nicholask42** [comment]
I am experiencing an issue similar to this. I have an application that uses an http_listener for a web server. When I run the application manually there is no issue and all endpoints work properly. However, if I run it using systemd when I hit one of the endpoints the service crashes with a double free or corruption error. I was able to capture a gdb backtrace of this issue, which I have attached. The backtrace points to an issue with http_listener, as mentioned in the issue title.
[gdb.txt](https://github.com/microsoft/cpprestsdk/files/4470620/gdb.txt)

**Comment by nicholask42** [comment]
After further investigation it seems that the problem may stem from installing with `sudo apt-get install libcpprest-dev`. After uninstalling, then building and installing from source the problem is no longer present. I am still not completely sure what the root cause is, but this seems to have fixed the issue for me.
