### ISSUE TITLE
OpenSSL 1.1.1 support

### ISSUE THREAD

**Issue by guest512** [Microsoft/cpprestsdk#909]
Recently OpenSSL v1.1.1 was released and it will be a LTS version: https://www.openssl.org/blog/blog/2018/09/11/release111/

My questions are - does the cpprestsdk supports OpenSSL 1.1.1 officially when it builds on Windows and macOS ? If not, then do you have any plans to support it?

**Comment by BillyONeal** [comment]
At the moment the goal is to support whatever comes with vcpkg (which is a 1.0x OpenSSL), Ubuntu 16.04 (which is also 1.0.x, because that's what Azure deploys), Ubuntu 18.04 (because that's what's easy to do local Ubuntu development with ;), a 1.1x release), and whatever Homebrew installs on OSX (I believe a 1.0x release)

Most of our exposure to OpenSSL comes directly through asio, so it's more to do with what asio supports than what we do. 1.1x will probably work with sufficiently recent copies of Boost.

**Comment by guest512** [comment]
Thank you for the information.
