### ISSUE TITLE
uri_builder crash

### ISSUE THREAD

**Issue by opottone** [Microsoft/cpprestsdk#994]
This minimal program crashes:
```
#include "cpprest/uri.h"

int main()
{
    web::uri uri(U("http://127.0.0.1:34568/"));
}
```

The crash happens when the program is compiled with Visual Studio 2017 in Debug mode with Runtime Library set to "Multi-Threaded Debug (/MTd)" (Project properties -> C/C++ -> Code Generation -> Runtime Library)

The program crashes with error message

> Debug Assertion Failed!
File: minkernel/crts/ucrt/src/appcrt/heap/debug_heap.cpp
Line: 996
Expression: __acrt_first_block == header

**Comment by BillyONeal** [comment]
I just tried this under address sanitizer and it passes. What version are you looking at?

**Comment by opottone** [comment]
I'm using 2.10.8 (the version you get when you just run vcpkg install).

**Comment by opottone** [comment]
Yes that makes sense. Thank you @BillyONeal.

**Comment by opottone** [comment]
Though in neither case did I actively chose the wrong option, I just went with the defaults. What if static build were the default in vcpgk installation?

**Comment by BillyONeal** [comment]
The default when you make a new project in VS is to use the DLL variant of the CRT, which is also vcpkg's default. They both need to be changed at the same time. That said, it would be better if you got some kind of message from vcpkg that explained badness was happening rather than just deploying incorrect bits. At that point though, it becomes a vcpkg bug; there's nothing cpprestsdk can do here.
